# Generated by Django 3.2.9 on 2022-12-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(default='00446242', max_length=8, unique=True),
        ),
    ]
