# Generated by Django 3.2.9 on 2022-12-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0002_alter_giftcard_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(default='00302430', max_length=8, unique=True),
        ),
    ]
