# Generated by Django 3.2.9 on 2022-12-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0003_auto_20221225_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(default='950320', max_length=8, unique=True),
        ),
    ]
