# Generated by Django 3.2.9 on 2022-12-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifting', '0006_alter_giftcard_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(default='965477', max_length=8, unique=True),
        ),
    ]
