# Generated by Django 3.2.9 on 2021-11-13 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('balance', models.IntegerField(default=0)),
                ('master', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name=100000)),
                ('reference', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('epoch', models.IntegerField()),
                ('sender_bal', models.IntegerField()),
                ('recip_bal', models.IntegerField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='received', to='banking.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sent', to='banking.account')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
