# Generated by Django 3.2.9 on 2021-11-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('rate', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
