# Generated by Django 3.2.9 on 2021-11-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_conversionrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
